### ISSUE TITLE
No libssl was found in lxc container

### ISSUE THREAD

**Issue by dibu28** [maxim-saplin/xOPS-Console#1]
Tried to start app in Proxmox LXC container with Ubuntu 22 innstalled in container. Got this error:

```
./xOPS_Console_x64
No usable version of libssl was found
Aborted
```

**Comment by maxim-saplin** [comment]
Hi. Please try the following release: https://github.com/maxim-saplin/xOPS-Console/releases/download/1.2.3/xOPS_Console
